# These are supported funding model platforms

github: sritajkumarpatel
# patreon: # Replace with your Patreon
# open_collective: # Replace with your Open Collective
# ko_fi: # Replace with your Ko-fi
# tidelift: # Replace with your Tidelift
# custom: # Replace with a custom link
